### ISSUE TITLE
Time selection wrong  when using the calendar to set a spesific time interval

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2402] opened 2024-05-03 09:37 UTC
![image](https://github.com/equinor/witsml-explorer/assets/123538108/91a0d780-a156-465c-b9ea-10685d597341)

As you can see it selects from 19:57 instead of 09:57

**Comment by eliasbruvik** [comment] 2024-05-14 07:08
Duplicate of #2411

**Closed as completed** 2024-05-22 11:01 UTC
Labels: Bug
